#!/usr/bin/env bash
# =============================================================================
# run_quic.sh — Run a single QUIC evaluation scenario.
#
# Launches the quic-client container against an already-running quic-server,
# waits for completion, then copies the timing log from the Docker volume
# to the host results directory.
#
# Usage:
#   run_quic.sh <kem_group> <network_label> <output_file> \
#               [sig_alg] [n_runs] [warmup_runs]
#
# Arguments:
#   kem_group      OQS-Provider KEM name, e.g. "mlkem768" or "x25519_mlkem768"
#   network_label  One of: ideal | low_loss | medium_loss | high_loss
#   output_file    Absolute path on the HOST where the CSV log will be written
#   sig_alg        Signature algorithm for the server cert (default: mldsa65)
#   n_runs         Number of measured handshakes           (default: 1000)
#   warmup_runs    Number of discarded warm-up runs        (default: 50)
#
# Notes:
#   - The KEM group is communicated to the QUIC binaries via OPENSSL_CONF,
#     which is generated by the Docker entrypoint scripts from QUIC_KEM_GROUP.
#   - Certificate validation is disabled on the QUIC client side because
#     self-signed PQC certificates are used (see src/quic/client.c).
#     The certificate is still transmitted, so bandwidth measurements are
#     accurate.
#
# Environment variables (optional overrides):
#   QUIC_SERVER_HOST  Hostname of the QUIC server container (default: quic-server)
#   QUIC_SERVER_PORT  Port of the QUIC server               (default: 4433)
#   COMPOSE_FILE      Path to docker-compose.yml            (default: auto-detect)
# =============================================================================
set -euo pipefail

# ── Arguments ─────────────────────────────────────────────────────────────────
KEM_GROUP="${1:?Usage: run_quic.sh <kem_group> <network_label> <output_file> [sig_alg] [n_runs] [warmup]}"
NET_LABEL="${2:?Missing network_label argument}"
OUTPUT_FILE="${3:?Missing output_file argument}"
SIG_ALG="${4:-mldsa65}"
N_RUNS="${5:-1000}"
WARMUP="${6:-50}"

# ── Configuration ─────────────────────────────────────────────────────────────
QUIC_SERVER_HOST="${QUIC_SERVER_HOST:-quic-server}"
QUIC_SERVER_PORT="${QUIC_SERVER_PORT:-4433}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

COMPOSE_FILE="${COMPOSE_FILE:-${PROJECT_ROOT}/docker-compose.yml}"

OUTPUT_LABEL="quic_${KEM_GROUP}_${NET_LABEL}"

# ── Logging helpers ────────────────────────────────────────────────────────────
log()  { echo "[run_quic] $*"; }
warn() { echo "[run_quic] WARN: $*" >&2; }
err()  { echo "[run_quic] ERROR: $*" >&2; }

# ── Pre-flight: verify the QUIC server container is running ───────────────────
log "Checking QUIC server container (${QUIC_SERVER_HOST})..."

SERVER_RUNNING=false
for attempt in $(seq 1 15); do
    CONTAINER_STATUS="$(docker inspect \
        --format='{{.State.Status}}' \
        "${QUIC_SERVER_HOST}" 2>/dev/null || echo "missing")"

    if [[ "${CONTAINER_STATUS}" == "running" ]]; then
        SERVER_RUNNING=true
        log "Server container is running (attempt ${attempt})."
        break
    fi
    sleep 2
done

if [[ "${SERVER_RUNNING}" == "false" ]]; then
    warn "QUIC server container '${QUIC_SERVER_HOST}' does not appear to be running."
    warn "Proceeding anyway — the client will time out if the server is unreachable."
fi

# ── Banner ────────────────────────────────────────────────────────────────────
log "────────────────────────────────────────────────────────────"
log " protocol : QUIC (MsQuic / TLS 1.3 integrated)"
log " kem      : ${KEM_GROUP}"
log " sig_alg  : ${SIG_ALG}"
log " network  : ${NET_LABEL}"
log " runs     : ${N_RUNS} (+${WARMUP} warmup)"
log " output   : ${OUTPUT_FILE}"
log "────────────────────────────────────────────────────────────"

# ── Restart the QUIC server with the correct KEM group ───────────────────────
#
# Unlike TLS (where the server accepts any group the client offers), MsQuic
# negotiates the QUIC transport parameters at the same time as TLS.  We
# restart the server container with the matching QUIC_KEM_GROUP so that both
# sides configure the same OpenSSL group via their OPENSSL_CONF files.
#
log "Restarting quic-server with KEM_GROUP=${KEM_GROUP} SIG_ALG=${SIG_ALG}..."

docker compose \
    --file "${COMPOSE_FILE}" \
    stop quic-server 2>/dev/null || true

docker compose \
    --file "${COMPOSE_FILE}" \
    rm -f quic-server 2>/dev/null || true

QUIC_KEM_GROUP="${KEM_GROUP}" \
QUIC_SIG_ALG="${SIG_ALG}" \
    docker compose \
        --file "${COMPOSE_FILE}" \
        up -d quic-server

# Give the server a few seconds to initialise
log "Waiting for quic-server to initialise..."
sleep 4

# ── Run the QUIC client container ─────────────────────────────────────────────
START_TIME=$(date +%s%3N)

docker compose \
    --file "${COMPOSE_FILE}" \
    run \
    --rm \
    --no-deps \
    -e QUIC_KEM_GROUP="${KEM_GROUP}" \
    -e QUIC_SIG_ALG="${SIG_ALG}" \
    -e QUIC_SERVER_HOST="${QUIC_SERVER_HOST}" \
    -e QUIC_SERVER_PORT="${QUIC_SERVER_PORT}" \
    -e N_RUNS="${N_RUNS}" \
    -e WARMUP_RUNS="${WARMUP}" \
    -e OUTPUT_LABEL="${OUTPUT_LABEL}" \
    -e CERT_DIR="/certs" \
    -e RESULTS_DIR="/results" \
    quic-client

CLIENT_EXIT=$?
END_TIME=$(date +%s%3N)
ELAPSED_MS=$(( END_TIME - START_TIME ))

# ── Copy result from Docker volume to host output path ───────────────────────
HOST_OUT_DIR="$(dirname "${OUTPUT_FILE}")"
mkdir -p "${HOST_OUT_DIR}"

log "Copying results from Docker volume to ${OUTPUT_FILE}..."

COPY_EXIT=0
docker run \
    --rm \
    -v pqc-eval_results:/vol_results:ro \
    -v "${HOST_OUT_DIR}:/host_out" \
    alpine:latest \
    sh -c "cp /vol_results/${OUTPUT_LABEL}.log /host_out/ 2>/dev/null && \
           echo 'copy ok'" \
    || COPY_EXIT=$?

if [[ ${COPY_EXIT} -ne 0 ]]; then
    warn "Could not copy log from volume — the file may still be in the volume."
    warn "Manual extraction:"
    warn "  docker run --rm -v pqc-eval_results:/v alpine cat /v/${OUTPUT_LABEL}.log"
fi

# ── Validate the output file ──────────────────────────────────────────────────
ACTUAL_OUTPUT="${HOST_OUT_DIR}/${OUTPUT_LABEL}.log"

if [[ -f "${ACTUAL_OUTPUT}" ]]; then
    ROW_COUNT=$(( $(wc -l < "${ACTUAL_OUTPUT}") - 1 ))
    log "Output: ${ACTUAL_OUTPUT}  (${ROW_COUNT} data rows)"

    MIN_EXPECTED=$(( N_RUNS * 80 / 100 ))
    if [[ ${ROW_COUNT} -lt ${MIN_EXPECTED} ]]; then
        warn "Only ${ROW_COUNT}/${N_RUNS} rows written — possible high failure rate."
        warn "Check QUIC_KEM_GROUP support: some KEMs may not be available in this build."
    fi
else
    warn "Output file not found at ${ACTUAL_OUTPUT}"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
if [[ ${CLIENT_EXIT} -eq 0 ]]; then
    log "Scenario PASSED  (elapsed: ${ELAPSED_MS} ms)"
else
    warn "Scenario finished with exit code ${CLIENT_EXIT}  (elapsed: ${ELAPSED_MS} ms)"
fi

exit ${CLIENT_EXIT}
